### ISSUE TITLE
Conditionally load JS only where needed

### ISSUE THREAD

**Issue by mandiwise** [redacademy/evans-spring-2017#16]
You are enqueuing a lot of individual JS files in your theme—each of these require their own HTTP request, which will have an impact on performance. Look to see where you can combine any of these into one, and then selectively load these scripts only on pages where they're needed. 

See the example that came with `redstarter` currently on line 162 of your `functions.php` file. This script uses WP functions to check what template is being loaded, and only loads the comments JS where needed. Follow a similar approach for your templates!

**Comment by victorsalmon** [comment]
Thanks, patched in 2c86a93b89828c9ec4d6c858adcea1b97dcb6326.
