### ISSUE TITLE
Remove Demo Font Files

### ISSUE THREAD

**Issue by rcass** [redacademy/evans-spring-2017#19]
In the fonts folder, there are demo files (the ones ending in HTML) saved to the repo.

These don't need to be in your project at all so just remove them!

- [x] Delete josefinsans-bold-demo.html

- [x] Delete lato-regular-demo.html

- [x] Delete josefinsans-regular-demo.html

- [x] Delete selima_-demo.html

**Comment by madcunian** [comment]
Done - 0405123aa745bf439587305e78c130659d91de7c
